@startuml
left to right direction
actor Prestamista as P
actor Solicitante as S
actor Administrador as A

Package BancoDiario {

usecase "Gestionar prestamos" as UC1
usecase "Generar acuerdos" as UC2
usecase "Consultar informacion" as UC3
usecase "Validar solicitudes" as UC4
usecase "Gestionar pagos" as UC5
usecase "Gestionar usuarios" as UC6
usecase "Administrar sistema" as UC7

}

P -- UC1
P -- UC2
P -- UC3
P -- UC4

S -- UC1
S -- UC5
S -- UC3

UC1 -- A
UC7 -- A
UC3 -- A
@enduml
