
package marcredito.view;

import marcredito.controller.ControladorBanco;


/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    private final ControladorBanco controller;

    public Login() {
        this.controller = null;   // para el diseñador
        initComponents();
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            new Register(controller).setVisible(true);
            dispose();
            }
        });
    }

    public Login(ControladorBanco controller) {
        this.controller = controller;
        initComponents();
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            new Register(controller).setVisible(true);
            dispose();
            }
        });
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        BarritaAbajo = new javax.swing.JPanel();
        SeguroLabel = new javax.swing.JLabel();
        asistLabel = new javax.swing.JLabel();
        comproLabel = new javax.swing.JLabel();
        FondoLoginDentro = new javax.swing.JPanel();
        idTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        passTxt = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        ingresoButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BarritaAzul = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarritaAbajo.setBackground(new java.awt.Color(204, 255, 255));
        BarritaAbajo.setForeground(new java.awt.Color(255, 255, 255));
        BarritaAbajo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SeguroLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        SeguroLabel.setForeground(new java.awt.Color(102, 102, 102));
        SeguroLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verified.png"))); // NOI18N
        SeguroLabel.setText("   SEGURO");
        BarritaAbajo.add(SeguroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 200, 68));

        asistLabel.setBackground(new java.awt.Color(255, 255, 255));
        asistLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        asistLabel.setForeground(new java.awt.Color(102, 102, 102));
        asistLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/audio-headset-of-auriculars-with-microphone-included.png"))); // NOI18N
        asistLabel.setText("    ASISTENCIA 24/7");
        BarritaAbajo.add(asistLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 240, 70));

        comproLabel.setBackground(new java.awt.Color(255, 255, 255));
        comproLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        comproLabel.setForeground(new java.awt.Color(102, 102, 102));
        comproLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/leaf.png"))); // NOI18N
        comproLabel.setText("  COMPROMETIDOS");
        BarritaAbajo.add(comproLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 250, 70));

        Background.add(BarritaAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1010, 90));

        FondoLoginDentro.setBackground(new java.awt.Color(255, 255, 255));
        FondoLoginDentro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 100, true));
        FondoLoginDentro.setToolTipText("");
        FondoLoginDentro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idTxt.setForeground(new java.awt.Color(153, 153, 153));
        idTxt.setText("Ingresar usuario de la cuenta");
        idTxt.setBorder(null);
        idTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        idTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idTxtMousePressed(evt);
            }
        });
        idTxt.addActionListener(this::idTxtActionPerformed);
        FondoLoginDentro.add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 300, 30));

        jSeparator1.setAlignmentX(100.0F);
        jSeparator1.setMinimumSize(new java.awt.Dimension(100, 0));
        FondoLoginDentro.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        passTxt.setText("*******");
        passTxt.setToolTipText("");
        passTxt.setBorder(null);
        passTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTxtMousePressed(evt);
            }
        });
        passTxt.addActionListener(this::passTxtActionPerformed);
        FondoLoginDentro.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 300, 30));
        FondoLoginDentro.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 300, 10));
        FondoLoginDentro.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 300, 10));

        ingresoButton.setBackground(new java.awt.Color(51, 204, 255));
        ingresoButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ingresoButton.setForeground(new java.awt.Color(255, 255, 255));
        ingresoButton.setText("INGRESAR");
        ingresoButton.setToolTipText("");
        ingresoButton.setBorder(null);
        ingresoButton.addActionListener(this::ingresoButtonActionPerformed);
        FondoLoginDentro.add(ingresoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 120, 50));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("¡Bienvenido de nuevo!");
        FondoLoginDentro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 260, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Contraseña ");
        FondoLoginDentro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Ingrese cuenta mar credito");
        FondoLoginDentro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        FondoLoginDentro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/padlock.png"))); // NOI18N
        FondoLoginDentro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 30, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lock.png"))); // NOI18N
        FondoLoginDentro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 130, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Usuario");
        FondoLoginDentro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        Background.add(FondoLoginDentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 390, 460));

        BarritaAzul.setBackground(new java.awt.Color(153, 255, 255));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Registro");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("¿Todavia no tienes una cuenta?");
        jLabel11.setToolTipText("");

        javax.swing.GroupLayout BarritaAzulLayout = new javax.swing.GroupLayout(BarritaAzul);
        BarritaAzul.setLayout(BarritaAzulLayout);
        BarritaAzulLayout.setHorizontalGroup(
            BarritaAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarritaAzulLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(70, 70, 70))
        );
        BarritaAzulLayout.setVerticalGroup(
            BarritaAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarritaAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BarritaAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        Background.add(BarritaAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 390, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mar Credito logo 2.0.png"))); // NOI18N
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 330, 170));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDO GUI.png"))); // NOI18N
        Fondo.setText("jLabel1");
        Background.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1010, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void idTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idTxtMousePressed
        if (idTxt.getText().equals("Ingresar usuario de la cuenta")) {
        idTxt.setText("");
    }
    }//GEN-LAST:event_idTxtMousePressed

    private void passTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMousePressed
        if (passTxt.getText().equals("*******")) {
            passTxt.setText("");
        }
    }//GEN-LAST:event_passTxtMousePressed

    private void ingresoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoButtonActionPerformed
        if (controller == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ejecuta el proyecto desde App (no desde el main del Login).");
            return;
        }

        String id = idTxt.getText().trim();
        marcredito.model.Usuario u = controller.buscarUsuarioPorId(id);

        if (u == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario no encontrado");
        } else if (u instanceof marcredito.model.Solicitante s) {
                new MenuSolicitante(controller, s).setVisible(true);
                this.dispose();

            } else if (u instanceof marcredito.model.Prestamista p) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "El módulo de Prestamista está en construcción.",
                    "En construcción", javax.swing.JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_ingresoButtonActionPerformed

    private void passTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTxtActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
    }//GEN-LAST:event_jLabel3MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel BarritaAbajo;
    private javax.swing.JPanel BarritaAzul;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel FondoLoginDentro;
    private javax.swing.JLabel SeguroLabel;
    private javax.swing.JLabel asistLabel;
    private javax.swing.JLabel comproLabel;
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton ingresoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField passTxt;
    // End of variables declaration//GEN-END:variables
}
