package marcredito.view;

import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import marcredito.controller.ControladorBanco;
import java.util.List;
import javax.swing.JOptionPane;
import marcredito.model.Prestamo;


public class MenuPrestamista extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrestamista.class.getName());

    private final ControladorBanco controller;
    private final marcredito.model.Prestamista prestamista;

    public MenuPrestamista(ControladorBanco controller, marcredito.model.Prestamista prestamista) {
        this.controller = controller;
        this.prestamista = prestamista;

        initComponents();
        configurarTabla();        
        cargarSolicitudes();
        actualizarVista();
    } 

    public MenuPrestamista() {
        controller = null;
        prestamista = null;
        initComponents();
    }   
    
    
    private void configurarTabla() {
        
        DefaultTableModel nuevoModelo = new DefaultTableModel(
            new Object[][]{},
            new String[]{"ID", "Solicitante", "Monto", "Plazo", "Total", "Estado"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tablaSolicitudes.setModel(nuevoModelo);

        tablaSolicitudes.setEnabled(true);
        tablaSolicitudes.setRowSelectionAllowed(true);
        tablaSolicitudes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        tablaSolicitudes.setTableHeader(null);
        jScrollPane1.setColumnHeaderView(null);

    }
    
   private void cargarSolicitudes() {
        DefaultTableModel modelo = (DefaultTableModel) tablaSolicitudes.getModel();
        modelo.setRowCount(0);

        if (controller == null || prestamista == null) return;

        List<Prestamo> prestamos = controller.getPrestamos();
        for (Prestamo p : prestamos) {
            if (p.getPrestamista() != null && p.getPrestamista().getId().equals(prestamista.getId())) {
                modelo.addRow(new Object[] {
                    p.getIdPrestamo(),
                    p.getSolicitante().getNombre(),
                    p.getMonto(),
                    p.getAcuerdo().getPlazoMeses() + " meses",
                    p.calcularTotalPagar(),
                    p.getEstado()
                });
            }
        }
    }
    
    private void actualizarVista() {

        tablaSolicitudes.setTableHeader(null);
        tablaSolicitudes.setEnabled(true); 
        tablaSolicitudes.setRowSelectionAllowed(true);
        tablaSolicitudes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        if (tablaSolicitudes.getRowCount() == 0) {
            //Mostrar tabla vacia
            lblSinSolicitudes.setVisible(true);            
            
            //Ocultar tabla
            tablaSolicitudes.setVisible(false);
            jScrollPane1.setVisible(false);            
            btnVerDetalles.setVisible(false);
            } else {
                lblSinSolicitudes.setVisible(false);
                                
                //Mostrar tabla
                tablaSolicitudes.setVisible(true);
                jScrollPane1.setVisible(true);                
                btnVerDetalles.setVisible(true);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSinSolicitudes = new javax.swing.JLabel();
        btnVerDetalles = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSolicitudes = new javax.swing.JTable();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSinSolicitudes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSinSolicitudes.setText("¡No hay prestamos pendientes!");
        getContentPane().add(lblSinSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        btnVerDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bttn_details_s.png"))); // NOI18N
        btnVerDetalles.setBorderPainted(false);
        btnVerDetalles.setContentAreaFilled(false);
        btnVerDetalles.setDefaultCapable(false);
        btnVerDetalles.addActionListener(this::btnVerDetallesActionPerformed);
        getContentPane().add(btnVerDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 90, 30));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setOpaque(false);

        tablaSolicitudes.setBackground(new java.awt.Color(219, 219, 219));
        tablaSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Solicitante", "Monto", "Plazo", "Interes", "Estado"
            }
        ));
        tablaSolicitudes.setEnabled(false);
        tablaSolicitudes.setOpaque(false);
        tablaSolicitudes.setRowSelectionAllowed(false);
        tablaSolicitudes.setShowGrid(false);
        tablaSolicitudes.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaSolicitudesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tablaSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSolicitudesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSolicitudes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 580, 210));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bkg_presta.png"))); // NOI18N
        Fondo.setText("jLabel1");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetallesActionPerformed
        int row = tablaSolicitudes.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona una solicitud");
            return;
        }

        String idPrestamo = (String) tablaSolicitudes.getValueAt(row, 0);
        Prestamo prestamo = null;
        for (Prestamo p : controller.getPrestamos()) {
            if (p.getIdPrestamo().equals(idPrestamo)) {
                prestamo = p;
                break;
            }
        }
        if (prestamo == null) {
            JOptionPane.showMessageDialog(this, "No se encontró el préstamo.");
            return;
        }

        // Arma el mensaje con toda la info del préstamo
        String mensaje = "ID: " + prestamo.getIdPrestamo() + "\n"
            + "Solicitante: " + prestamo.getSolicitante().getNombre() + "\n"
            + "Monto: $" + prestamo.getMonto() + "\n"
            + "Plazo: " + prestamo.getAcuerdo().getPlazoMeses() + " meses\n"
            + "Interés: " + prestamo.getAcuerdo().getInteres() + "%\n"
            + "Total a pagar: " + prestamo.calcularTotalPagar() + "\n"
            + "Estado: " + prestamo.getEstado();
        if (!prestamo.getEstado().equalsIgnoreCase("Pendiente") && prestamo.getMotivo() != null) {
            mensaje += "\nMotivo: " + prestamo.getMotivo();
        }

        // Si está pendiente, puede aprobar/rechazar, sino solo muestra detalles
        if (prestamo.getEstado().equalsIgnoreCase("Pendiente")) {
            int opcion = JOptionPane.showOptionDialog(
                this,
                mensaje + "\n\n¿Quieres aprobar o rechazar este préstamo?",
                "Gestión de solicitud",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[] {"Aprobar", "Rechazar"},
                "Aprobar"
            );
            if (opcion == 0) { // Aprobar
                String motivo = JOptionPane.showInputDialog(this, "Motivo de aprobación:");
                if (motivo != null && !motivo.trim().isEmpty()) {
                    prestamo.setEstado("Aprobado");
                    prestamo.setMotivo(motivo);
                    controller.actualizarPrestamo(prestamo);
                    cargarSolicitudes();
                    actualizarVista();
                    JOptionPane.showMessageDialog(this, "¡Préstamo aprobado!");
                }
            } else if (opcion == 1) { // Rechazar
                String motivo = JOptionPane.showInputDialog(this, "Motivo de rechazo:");
                if (motivo != null && !motivo.trim().isEmpty()) {
                    prestamo.setEstado("Rechazado");
                    prestamo.setMotivo(motivo);
                    controller.actualizarPrestamo(prestamo);
                    cargarSolicitudes();
                    actualizarVista();
                    JOptionPane.showMessageDialog(this, "¡Préstamo rechazado!");
                }
            }
        } else {
            // Si ya estaba procesado, solo muestra los detalles y motivo
            JOptionPane.showMessageDialog(this, mensaje, "Detalles del préstamo", JOptionPane.INFORMATION_MESSAGE);
        }     
    }//GEN-LAST:event_btnVerDetallesActionPerformed

    private void tablaSolicitudesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaSolicitudesAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaSolicitudesAncestorAdded

    private void tablaSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSolicitudesMouseClicked
    
    }//GEN-LAST:event_tablaSolicitudesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuSolicitante().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnVerDetalles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSinSolicitudes;
    private javax.swing.JTable tablaSolicitudes;
    // End of variables declaration//GEN-END:variables
}
