package marcredito.view;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import marcredito.controller.ControladorBanco;
import marcredito.model.Prestamo;


public class MenuSolicitante extends javax.swing.JFrame {
        
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuSolicitante.class.getName());

    private final ControladorBanco controller;
    private final marcredito.model.Solicitante solicitante;

    public MenuSolicitante(ControladorBanco controller, marcredito.model.Solicitante solicitante) {

        this.controller = controller;
        this.solicitante = solicitante;

        initComponents();

        cargarSolicitudes();
        actualizarVista();
    } 
    
    public MenuSolicitante() {
        controller = null;
        solicitante = null;
        initComponents();
    }
    
    private void cargarSolicitudes() {
        if (controller == null || solicitante == null) {
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) tablaSolicitudes.getModel();

        modelo.setRowCount(0);

        List<Prestamo> prestamos =
        controller.obtenerPrestamosDeUsuario(solicitante.getId());

        for (Prestamo p : prestamos) {

            modelo.addRow(new Object[]{
                p.getIdPrestamo(),
                solicitante.getNombre(),
                p.getMonto(),
                p.getAcuerdo().getPlazoMeses() + " meses",
                p.getAcuerdo().getInteres() + "%",
                p.getEstado()
            });
        }
    }
    
    private void actualizarVista() {

        tablaSolicitudes.setTableHeader(null);
        jScrollPane1.setColumnHeaderView(null);
        tablaSolicitudes.setEnabled(true);
        tablaSolicitudes.setRowSelectionAllowed(true);
        tablaSolicitudes.setColumnSelectionAllowed(false);
        tablaSolicitudes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaSolicitudes.setDefaultEditor(Object.class, null);
        
        if (tablaSolicitudes.getRowCount() == 0) {
            //Mostrar tabla vacia
            lblSinSolicitudes.setVisible(true);
            btnNuevaSolicitudGrande.setVisible(true);
            
            //Ocultar tabla
            tablaSolicitudes.setVisible(false);
            jScrollPane1.setVisible(false);
            btnNuevaSolicitudMini1.setVisible(false);
            btnVerDetalles.setVisible(false);
            } else {
                lblSinSolicitudes.setVisible(false);
                btnNuevaSolicitudGrande.setVisible(false);
                
                //Mostrar tabla
                tablaSolicitudes.setVisible(true);
                jScrollPane1.setVisible(true);
                btnNuevaSolicitudMini1.setVisible(true);
                btnVerDetalles.setVisible(true);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSinSolicitudes = new javax.swing.JLabel();
        btnNuevaSolicitudGrande = new javax.swing.JButton();
        btnVerDetalles = new javax.swing.JButton();
        btnNuevaSolicitudMini1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSolicitudes = new javax.swing.JTable();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSinSolicitudes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSinSolicitudes.setText("¡No hay solicitudes pendientes!");
        getContentPane().add(lblSinSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        btnNuevaSolicitudGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bttn_new_s.png"))); // NOI18N
        btnNuevaSolicitudGrande.setBorder(null);
        btnNuevaSolicitudGrande.setBorderPainted(false);
        btnNuevaSolicitudGrande.setContentAreaFilled(false);
        btnNuevaSolicitudGrande.setFocusPainted(false);
        btnNuevaSolicitudGrande.addActionListener(this::btnNuevaSolicitudGrandeActionPerformed);
        getContentPane().add(btnNuevaSolicitudGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 210, 70));

        btnVerDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bttn_details_s.png"))); // NOI18N
        btnVerDetalles.setBorderPainted(false);
        btnVerDetalles.setContentAreaFilled(false);
        btnVerDetalles.setDefaultCapable(false);
        btnVerDetalles.addActionListener(this::btnVerDetallesActionPerformed);
        getContentPane().add(btnVerDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, -1, -1));

        btnNuevaSolicitudMini1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bttn_new_s2.png"))); // NOI18N
        btnNuevaSolicitudMini1.setBorderPainted(false);
        btnNuevaSolicitudMini1.setContentAreaFilled(false);
        btnNuevaSolicitudMini1.setDefaultCapable(false);
        btnNuevaSolicitudMini1.addActionListener(this::btnNuevaSolicitudMini1ActionPerformed);
        getContentPane().add(btnNuevaSolicitudMini1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setOpaque(false);

        tablaSolicitudes.setBackground(new java.awt.Color(219, 219, 219));
        tablaSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Solicitante", "Monto", "Plazo", "Interés", "Estado"
            }
        ));
        tablaSolicitudes.setEnabled(false);
        tablaSolicitudes.setOpaque(false);
        tablaSolicitudes.setRowSelectionAllowed(false);
        tablaSolicitudes.setShowGrid(false);
        tablaSolicitudes.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaSolicitudesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tablaSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSolicitudesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSolicitudes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 167, 590, 310));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bkg_solici.png"))); // NOI18N
        Fondo.setText("jLabel1");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetallesActionPerformed
        int row = tablaSolicitudes.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona una solicitud para ver detalles.");
            return;
        }

        String id = String.valueOf(tablaSolicitudes.getValueAt(row, 0));
        String sol = String.valueOf(tablaSolicitudes.getValueAt(row, 1));
        String monto = String.valueOf(tablaSolicitudes.getValueAt(row, 2));
        String plazo = String.valueOf(tablaSolicitudes.getValueAt(row, 3));
        String interes = String.valueOf(tablaSolicitudes.getValueAt(row, 4));
        String estado = String.valueOf(tablaSolicitudes.getValueAt(row, 5));

        JOptionPane.showMessageDialog(this,
                "ID: " + id + "\n"
                + "Solicitante: " + sol + "\n"
                + "Monto: " + monto + "\n"
                + "Plazo: " + plazo + "\n"
                + "Interés: " + interes + "\n"
                + "Estado: " + estado,
                "Detalle de solicitud",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnVerDetallesActionPerformed

    private void btnNuevaSolicitudGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaSolicitudGrandeActionPerformed
        crearNuevaSolicitud();
    }//GEN-LAST:event_btnNuevaSolicitudGrandeActionPerformed

    private void btnNuevaSolicitudMini1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaSolicitudMini1ActionPerformed
        crearNuevaSolicitud();
    }//GEN-LAST:event_btnNuevaSolicitudMini1ActionPerformed

    private void tablaSolicitudesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaSolicitudesAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaSolicitudesAncestorAdded

    private void tablaSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSolicitudesMouseClicked
    
    }//GEN-LAST:event_tablaSolicitudesMouseClicked

    private void crearNuevaSolicitud() {
        if (controller == null || solicitante == null) {
            return;
        }

        String montoStr = JOptionPane.showInputDialog(this, "Monto del préstamo:");
        if (montoStr == null) {
            return;
        }

        String plazoStr = JOptionPane.showInputDialog(this, "Plazo (meses):");
        if (plazoStr == null) {
            return;
        }

        double monto;
        int plazo;
        try {
            monto = Double.parseDouble(montoStr.trim());
            plazo = Integer.parseInt(plazoStr.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Monto o plazo inválido.");
            return;
        }

        String idPrestamista = JOptionPane.showInputDialog(this, "ID del prestamista (ej: P1):");
        if (idPrestamista == null) {
            return;
        }

        controller.crearPrestamo(monto, plazo, 5.0, solicitante.getId(), idPrestamista.trim());
        JOptionPane.showMessageDialog(this, "Solicitud creada y enviada (estado: Pendiente).");
        cargarSolicitudes();
        actualizarVista();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuSolicitante().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnNuevaSolicitudGrande;
    private javax.swing.JButton btnNuevaSolicitudMini1;
    private javax.swing.JButton btnVerDetalles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSinSolicitudes;
    private javax.swing.JTable tablaSolicitudes;
    // End of variables declaration//GEN-END:variables
}
