/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package marcredito.view;

import marcredito.controller.ControladorBanco;
/**
 *
 * @author User
 */
public class Register extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());

    /**
     * Creates new form Login
     */
    
    private final ControladorBanco controller;
    
    public Register() {
        this.controller = null;
        initComponents();
    }

    public Register(ControladorBanco controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        Background = new javax.swing.JPanel();
        BarritaAbajo = new javax.swing.JPanel();
        SeguroLabel = new javax.swing.JLabel();
        asistLabel = new javax.swing.JLabel();
        comproLabel = new javax.swing.JLabel();
        BarritaAzul = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FondoLoginDentro = new javax.swing.JPanel();
        idTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        passTxt = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        ingresoButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        contraTxt1 = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarritaAbajo.setBackground(new java.awt.Color(204, 255, 255));
        BarritaAbajo.setForeground(new java.awt.Color(255, 255, 255));
        BarritaAbajo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SeguroLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        SeguroLabel.setForeground(new java.awt.Color(102, 102, 102));
        SeguroLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verified.png"))); // NOI18N
        SeguroLabel.setText("   SEGURO");
        BarritaAbajo.add(SeguroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 200, 68));

        asistLabel.setBackground(new java.awt.Color(255, 255, 255));
        asistLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        asistLabel.setForeground(new java.awt.Color(102, 102, 102));
        asistLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/audio-headset-of-auriculars-with-microphone-included.png"))); // NOI18N
        asistLabel.setText("    ASISTENCIA 24/7");
        BarritaAbajo.add(asistLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 240, 70));

        comproLabel.setBackground(new java.awt.Color(255, 255, 255));
        comproLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        comproLabel.setForeground(new java.awt.Color(102, 102, 102));
        comproLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/leaf.png"))); // NOI18N
        comproLabel.setText("  COMPROMETIDOS");
        BarritaAbajo.add(comproLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 260, 70));

        Background.add(BarritaAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1010, 90));

        BarritaAzul.setBackground(new java.awt.Color(153, 255, 255));
        BarritaAzul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("¿Ya tienes una cuenta?");
        jLabel11.setToolTipText("");
        BarritaAzul.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 20));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Inicia sesion ");
        BarritaAzul.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 20));

        Background.add(BarritaAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 390, 60));

        FondoLoginDentro.setBackground(new java.awt.Color(255, 255, 255));
        FondoLoginDentro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 100, true));
        FondoLoginDentro.setToolTipText("");
        FondoLoginDentro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idTxt.setForeground(new java.awt.Color(153, 153, 153));
        idTxt.setText("Ingrese su nombre");
        idTxt.setBorder(null);
        idTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        idTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idTxtMousePressed(evt);
            }
        });
        idTxt.addActionListener(this::idTxtActionPerformed);
        FondoLoginDentro.add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 300, 30));

        jSeparator1.setAlignmentX(100.0F);
        jSeparator1.setMinimumSize(new java.awt.Dimension(100, 0));
        FondoLoginDentro.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        passTxt.setText("*******");
        passTxt.setToolTipText("");
        passTxt.setBorder(null);
        passTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTxtMousePressed(evt);
            }
        });
        passTxt.addActionListener(this::passTxtActionPerformed);
        FondoLoginDentro.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 300, 30));
        FondoLoginDentro.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 300, 10));
        FondoLoginDentro.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 300, 10));

        ingresoButton.setBackground(new java.awt.Color(51, 204, 255));
        ingresoButton.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ingresoButton.setForeground(new java.awt.Color(255, 255, 255));
        ingresoButton.setText("CREAR");
        ingresoButton.setToolTipText("");
        ingresoButton.setBorder(null);
        ingresoButton.addActionListener(this::ingresoButtonActionPerformed);
        FondoLoginDentro.add(ingresoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 120, 50));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("       Crea tu cuenta");
        FondoLoginDentro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 260, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Contraseña ");
        FondoLoginDentro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Unete a Mar credito e inicia tu camino");
        FondoLoginDentro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        FondoLoginDentro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/padlock.png"))); // NOI18N
        FondoLoginDentro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 30, 40));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Nombre ");
        FondoLoginDentro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        contraTxt1.setText("******9");
        contraTxt1.setToolTipText("");
        contraTxt1.setBorder(null);
        contraTxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contraTxt1MousePressed(evt);
            }
        });
        contraTxt1.addActionListener(this::contraTxt1ActionPerformed);
        FondoLoginDentro.add(contraTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 300, 30));
        FondoLoginDentro.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 300, 10));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/padlock.png"))); // NOI18N
        FondoLoginDentro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 30, 40));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Repetir contraseña");
        FondoLoginDentro.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/añadir (1)23.png"))); // NOI18N
        FondoLoginDentro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 90, 90));

        Background.add(FondoLoginDentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 390, 460));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mar Credito logo 2.0.png"))); // NOI18N
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 330, 170));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDO GUI.png"))); // NOI18N
        Fondo.setText("jLabel1");
        Background.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1010, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void idTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idTxtMousePressed
        if (idTxt.getText().equals("Ingrese su nombre")) {
        idTxt.setText(""); 
        }
    }//GEN-LAST:event_idTxtMousePressed

    private void passTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMousePressed
        if (passTxt.getText().equals("*******")) {
            passTxt.setText("");
        }
    }//GEN-LAST:event_passTxtMousePressed

    private void ingresoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoButtonActionPerformed
        String nombre = idTxt.getText().trim();

        String pass = new String(passTxt.getPassword());
        String confirm = new String(contraTxt1.getPassword());

        if (nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ingrese un nombre.");
            return;
        }

        if (!pass.equals(confirm)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Las contraseñas no coinciden.");
            return;
        }

        // Generar ID automático
        String id = "MC" + ((int)(Math.random() * 90) + 10);

        // Correo ficticio temporal
        String correo = nombre.replace(" ", "").toLowerCase() + "@mail.com";

        // Registrar solicitante
        controller.registrarSolicitante(id, nombre, correo);

        javax.swing.JOptionPane.showMessageDialog(this,
                "Cuenta creada correctamente.\nTu ID es: " + id);

        // Volver al login
        new Login(controller).setVisible(true);
        dispose();
    }//GEN-LAST:event_ingresoButtonActionPerformed

    private void passTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTxtActionPerformed

    private void contraTxt1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraTxt1MousePressed
       if (contraTxt1.getText().equals("******9")) {
            contraTxt1.setText("");
        }
    }//GEN-LAST:event_contraTxt1MousePressed

    private void contraTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraTxt1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel BarritaAbajo;
    private javax.swing.JPanel BarritaAzul;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel FondoLoginDentro;
    private javax.swing.JLabel SeguroLabel;
    private javax.swing.JLabel asistLabel;
    private javax.swing.JLabel comproLabel;
    private javax.swing.JPasswordField contraTxt1;
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton ingresoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JPasswordField passTxt;
    // End of variables declaration//GEN-END:variables
}
